[package]
name = "creature-creator-pipelines"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
creature-creator-implicit-sampler = { path = "../CreatureCreatorImplicitSampler"}

nalgebra = "0.32"
metal = "0.27"
