[package]
name = "creature-creator-pipelines"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
rand = "0.8"
nalgebra = "0.32"
metal = "0.27"
